# Generated by Django 4.0.2 on 2022-02-18 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gog',
            new_name='Dog',
        ),
    ]
