# Generated by Django 3.1 on 2022-03-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0002_rename_gog_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
